// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDms35llqfUqCebMy0tHce5Z8SwvvT0d0c',
    appId: '1:620577058988:web:9bae564d6d69c935616f09',
    messagingSenderId: '620577058988',
    projectId: 'tp-flutter-12d8f',
    authDomain: 'tp-flutter-12d8f.firebaseapp.com',
    storageBucket: 'tp-flutter-12d8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLNz3GqrBJZCRWh_Q9PlhOb5nVsnn-z7c',
    appId: '1:620577058988:android:c1973fd42150645d616f09',
    messagingSenderId: '620577058988',
    projectId: 'tp-flutter-12d8f',
    storageBucket: 'tp-flutter-12d8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7uMs8pwzM75aWeiwOB9AYm0AyIHHw9eg',
    appId: '1:620577058988:ios:558f25bb69adba0e616f09',
    messagingSenderId: '620577058988',
    projectId: 'tp-flutter-12d8f',
    storageBucket: 'tp-flutter-12d8f.firebasestorage.app',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7uMs8pwzM75aWeiwOB9AYm0AyIHHw9eg',
    appId: '1:620577058988:ios:558f25bb69adba0e616f09',
    messagingSenderId: '620577058988',
    projectId: 'tp-flutter-12d8f',
    storageBucket: 'tp-flutter-12d8f.firebasestorage.app',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDms35llqfUqCebMy0tHce5Z8SwvvT0d0c',
    appId: '1:620577058988:web:f3dba13074c805ce616f09',
    messagingSenderId: '620577058988',
    projectId: 'tp-flutter-12d8f',
    authDomain: 'tp-flutter-12d8f.firebaseapp.com',
    storageBucket: 'tp-flutter-12d8f.firebasestorage.app',
  );
}
